topics:
- "/eddy/sonar/profile"
- "/eddy/sonar/history"
- "/eddy/sonar/distance"
- "/eddy/gps/fix"
- "/eddy/gps/time_reference"
- "/eddy/gps/vel"
- "/eddy/imu/accel"
- "/eddy/imu/gravity"
- "/eddy/imu/imu"
- "/eddy/imu/magnetic_field"
- "/eddy/camera/image_raw"
