<?xml version="1.0" ?>
<robot name="ultron" xmlns:xacro="http://ros.org/wiki/xacro">
	
	<!-- All offsets are placeholder values ATM -->
	<xacro:property name="thruster_offset_y" value="0.08"/>
	<xacro:property name="thruster_offset_z" value="0.023"/>
	
	<xacro:property name="imu_offset_x" value="-0.032"/>
	<xacro:property name="imu_offset_y" value="0.0"/>
	<xacro:property name="imu_offset_z" value="0.068"/>
	
	<xacro:property name="gps_offset_x" value="-0.032"/>
	<xacro:property name="gps_offset_y" value="0.0"/>
	<xacro:property name="gps_offset_z" value="0.068"/>
	
	<xacro:property name="sonar_offset_x" value="-0.032"/>
	<xacro:property name="sonar_offset_y" value="0.0"/>
	<xacro:property name="sonar_offset_z" value="0.068"/>
	
	<material name="blue">
		<color rgba="0.1 0.1 0.5 1.0"/>
	</material>
	
	<link name="base_footprint"/>
	
	<joint name="base_joint" type="fixed">
		<parent link="base_footprint"/>
		<child link="base_link"/>
 		<origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
	</joint>
	
	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="1.57 0 0"/>
			<geometry>
				<mesh filename="package://eddy_description/meshes/eddy.stl" scale="1.0 1.0 1.0"/>
			</geometry>
		</visual>
	</link>
	
	<!-- Accutuated Joint (Thruster Blades) -->
	
	
	<!-- Left Thruster -->
	
	<joint name="thruster_left_joint" type="continuous">
		<parent link="base_link"/>
		<child link="thruster_left_link"/>
		<origin xyz="0.0 ${thruster_offset_y} ${thruster_offset_z}" rpy="-1.57 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>
	
	<link name="thruster_left_link">
		<visual>
			<origin xyz="0 0 0" rpy="1.57 0 0"/>
			<geometry>
				<mesh filename="package://eddy_description/meshes/thruster.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="blue"/>
		</visual>
	</link>
	
	<!-- Right Thruster -->
	
	<joint name="thruster_right_joint" type="continuous">
		<parent link="base_link"/>
		<child link="thruster_right_link"/>
		<origin xyz="0.0 ${-1 * thruster_offset_y} ${thruster_offset_z}" rpy="-1.57 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>
	
	<link name="thruster_right_link">
		<visual>
			<origin xyz="0 0 0" rpy="1.57 0 0"/>
			<geometry>
				<mesh filename="package://eddy_description/meshes/thruster.stl" scale="0.001 0.001 0.001"/>
			</geometry>
			<material name="blue"/>
		</visual>
	</link>

	<!-- Sensor frames  -->
	
	<!-- IMU frame  -->

	<joint name="imu_joint" type="fixed">
		<parent link="base_link"/>
		<child link="imu_link"/>
		<origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="0 0 0"/>
	</joint>
	
	<link name="imu_link"/>
	
	<!-- GPS frame  -->
	
	<joint name="gps_joint" type="fixed">
		<parent link="base_link"/>
		<child link="gps_link"/>
		<origin xyz="${gps_offset_x} ${gps_offset_y} ${gps_offset_z}" rpy="0 0 0"/>
	</joint>
	
	<link name="gps_link"/>
	
	<!-- Sonar frame  -->
	
	<joint name="sonar_joint" type="fixed">
		<parent link="base_link"/>
		<child link="sonar_link"/>
		<origin xyz="${sonar_offset_x} ${sonar_offset_y} ${sonar_offset_z}" rpy="0 0 0"/>
	</joint>
	
	<link name="sonar_link"/>
	
	
</robot>
